index:
    path: /
    controller: App\Controller\ApiController::indexAction
    methods: GET

add_game:
    path: /api/game
    controller: App\Controller\ApiController::addGameAction
    methods: POST

edit_game:
    path: /api/game/{id}
    controller: App\Controller\ApiController::editGameAction
    methods: PUT

show_game:
    path: /api/game/{id}
    controller: App\Controller\ApiController::showGameAction
    methods: GET
